version: '3'
services:
  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123123
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=123123@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=123123
    ports:
      - '5555:80'
    volumes:
      - ./docker/pgadmin/data:/var/lib/pgadmin
    depends_on:
      - postgres